### ISSUE TITLE
Cannot run serp API healthcheck job

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/cfc-schedules-tweet#53]
```bash
2024-02-09T01:00:34.451428+00:00 heroku[scheduler.8814]: State changed from starting to up
2024-02-09T01:00:34.818203+00:00 app[scheduler.8814]: internal/modules/cjs/loader.js:818
2024-02-09T01:00:34.818281+00:00 app[scheduler.8814]: throw err;
2024-02-09T01:00:34.818281+00:00 app[scheduler.8814]: ^
2024-02-09T01:00:34.818281+00:00 app[scheduler.8814]:
2024-02-09T01:00:34.818282+00:00 app[scheduler.8814]: Error: Cannot find module '/app/builds/jobs/serp-api-healthcheck.js'
2024-02-09T01:00:34.818282+00:00 app[scheduler.8814]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
2024-02-09T01:00:34.818282+00:00 app[scheduler.8814]: at Function.Module._load (internal/modules/cjs/loader.js:667:27)
2024-02-09T01:00:34.818282+00:00 app[scheduler.8814]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
2024-02-09T01:00:34.818283+00:00 app[scheduler.8814]: at internal/main/run_main_module.js:17:47 {
2024-02-09T01:00:34.818283+00:00 app[scheduler.8814]: code: 'MODULE_NOT_FOUND',
2024-02-09T01:00:34.818283+00:00 app[scheduler.8814]: requireStack: []
2024-02-09T01:00:34.818284+00:00 app[scheduler.8814]: }
```

**Comment by wildan3105** [comment]
typo
